In [73]:
import numpy as np

In [2]:
import tensorflow as tf

In [273]:
import sklearn

In [1]:
from tensorflow import keras

In [4]:
from tensorflow.keras.models import Sequential

In [7]:
from tensorflow.keras import Model,Input

In [8]:
from tensorflow.keras import datasets

In [12]:
from tensorflow.keras.layers import Dense,Conv2D,MaxPooling2D,BatchNormalization,Flatten

In [322]:
from tensorflow.keras.layers import Dropout

In [91]:
from sklearn.preprocessing import OneHotEncoder

In [266]:
from sklearn.svm import SVR

In [275]:
from sklearn import metrics

In [279]:
from sklearn import grid_search

d:\program files\python\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
d:\program files\python\lib\site-packages\sklearn\grid_search.py:42: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
  DeprecationWarning)


In [274]:
dir(sklearn)

['_ASSUME_FINITE',
 '__SKLEARN_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__check_build',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_contextmanager',
 'base',
 'clone',
 'config_context',
 'exceptions',
 'externals',
 'feature_selection',
 'get_config',
 'linear_model',
 'logger',
 'logging',
 'metrics',
 'model_selection',
 'neighbors',
 'os',
 'preprocessing',
 'random_projection',
 're',
 'set_config',
 'setup_module',
 'svm',
 'sys',
 'utils',
 'warnings']

In [65]:
DATAS=datasets.mnist.load_data()

In [66]:
DATAS[0][0].shape

(60000, 28, 28)

In [67]:
DATAS[0][1].shape

(60000,)

In [68]:
DATAS[1][0].shape

(10000, 28, 28)

In [69]:
DATAS[1][1].shape

(10000,)

In [70]:
X_train=DATAS[0][0]
y_train=DATAS[0][1]
X_test=DATAS[1][0]
y_test=DATAS[1][1]

In [93]:
encoder=OneHotEncoder()

In [98]:
encoder.fit([[i] for i in range(10)])

OneHotEncoder(categorical_features='all', dtype=<class 'numpy.float64'>,
       handle_unknown='error', n_values='auto', sparse=True)

In [100]:
y_train.shape

(60000,)

In [162]:
y_train_transformed=encoder.transform(np.array(y_train).reshape(-1,1)).toarray()

In [163]:
y_test_transformed=encoder.transform(np.array(y_test).reshape(-1,1)).toarray()

In [97]:
[[i] for i in range(10)]

[[0], [1], [2], [3], [4], [5], [6], [7], [8], [9]]

In [116]:
inputs=Input(shape=(28,28,1))

In [117]:
conv_1=Conv2D(32,(2,2),activation='relu',padding='same')(inputs)

In [141]:
pooled_1=MaxPooling2D((2,2))(conv_1)

In [142]:
normed=BatchNormalization()(pooled_1)

In [143]:
conv_2=Conv2D(64,(2,2),activation='relu',padding='same')(normed)

In [144]:
pooled_2=MaxPooling2D((2,2))(conv_2)

In [145]:
flatted=Flatten()(pooled_2)

In [146]:
fulcnct=Dense(500,activation='relu')(flatted)

In [147]:
predicted=Dense(10,activation='softmax')(fulcnct)

In [129]:
knt_model=Model(inputs=inputs,outputs=predicted)

In [130]:
knt_model.compile(loss='categorical_crossentropy',
                 optimizer='sgd',
                 metrics=['accuracy'])

In [131]:
knt_model.fit(X_train[:,:,:,np.newaxis],y_train_transformed)

Epoch 1/1
60000/60000 [==============================] - 91s 2ms/step - loss: 0.1703 - acc: 0.9490


In [138]:
x_holder=tf.placeholder(tf.float32,shape=(None,28,28,1))

In [140]:
conv_1=Conv2D(32,(2,2),activation='relu',padding='same')(x_holder)

In [148]:
y_holder=tf.placeholder(tf.float32,shape=(None,10))

In [152]:
loss=tf.reduce_mean(-tf.reduce_sum(tf.log(predicted)*y_holder,reduction_indices=[1]))

In [153]:
train=tf.train.AdamOptimizer(1e-4).minimize(loss)

In [154]:
sess=tf.Session()

In [170]:
sess.run(tf.initialize_all_variables())

In [171]:
sess.run(train,feed_dict={x_holder:X_train[:,:,:,np.newaxis],y_holder:y_train_transformed})
print(sess.run(loss,feed_dict={x_holder:X_train[:,:,:,np.newaxis],y_holder:y_train_transformed}))

nan


In [169]:
sess.run(loss,feed_dict={x_holder:X_train[:,:,:,np.newaxis],y_holder:y_train_transformed})

nan

In [175]:
boston_data=datasets.boston_housing.load_data()

57344/57026 [==============================] - 0s 4us/step


In [218]:
X_train_boston=boston_data[0][0]

In [387]:
X_train_boston[0:3].shape

(3, 13)

In [401]:
x_test=tf.placeholder(tf.float32,shape=(3,13))

In [402]:
nor_test=BatchNormalization()(x_test)

In [409]:
layer_nor_tf=tf.layers.batch_normalization(x_test,training=True)           #####居然必须把training设成True才行

In [572]:
sess.run(tf.initialize_all_variables())

In [412]:
nor_result=sess.run(layer_nor_tf,feed_dict={x_test:X_train_boston[0:3]})

In [422]:
np.mean(nor_result,axis=0)

array([ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
        4.7683716e-07, -1.5894572e-07,  7.9472862e-08, -1.5894572e-07,
        0.0000000e+00, -3.9736431e-08,  1.5894572e-07, -5.0862632e-06,
       -1.5894572e-07], dtype=float32)

In [219]:
y_train_boston=boston_data[0][1]

In [220]:
X_test_boston=boston_data[1][0]

In [221]:
y_test_boston=boston_data[1][1]

In [641]:
input_boston=Input(shape=(13,))

In [642]:
normed_boston=BatchNormalization()(input_boston,training=True)

In [643]:
layer1=Dense(600,activation='relu')(normed_boston)

In [644]:
drop1=Dropout(rate=0.4)(layer1)

In [645]:
layer2=Dense(1000,activation='relu')(drop1)

In [646]:
drop2=Dropout(rate=0.5)(layer2)

In [647]:
layer3=Dense(10,activation='softmax')(drop2)

In [648]:
layer4=Dense(1,activation=None)(layer3)

In [649]:
model_boston=Model(inputs=input_boston,outputs=layer4)

In [650]:
model_boston.compile(loss='mse',
                     optimizer='sgd')

In [651]:
model_boston.fit(X_train_boston,y_train_boston,epochs=100)

Epoch 1/100
404/404 [==============================] - 2s 5ms/step - loss: 446.0941
Epoch 2/100
404/404 [==============================] - 0s 443us/step - loss: 219.2348
Epoch 3/100
404/404 [==============================] - 0s 430us/step - loss: 130.4841
Epoch 4/100
404/404 [==============================] - 0s 346us/step - loss: 100.5120 0s - loss: 91.20
Epoch 5/100
404/404 [==============================] - 0s 344us/step - loss: 90.1150
Epoch 6/100
404/404 [==============================] - 0s 364us/step - loss: 86.4646
Epoch 7/100
404/404 [==============================] - 0s 537us/step - loss: 85.0304
Epoch 8/100
404/404 [==============================] - 0s 440us/step - loss: 73.3372
Epoch 9/100
404/404 [==============================] - 0s 369us/step - loss: 59.5285
Epoch 10/100
404/404 [==============================] - 0s 319us/step - loss: 51.8224
Epoch 11/100
404/404 [==============================] - 0s 336us/step - loss: 48.2550
Epoch 12/100
404/404 [======================

404/404 [==============================] - 0s 349us/step - loss: 16.1410
Epoch 97/100
404/404 [==============================] - 0s 349us/step - loss: 18.0126
Epoch 98/100
404/404 [==============================] - 0s 334us/step - loss: 17.0941
Epoch 99/100
404/404 [==============================] - 0s 374us/step - loss: 24.1891
Epoch 100/100
404/404 [==============================] - 0s 433us/step - loss: 17.6754


In [652]:
model_boston.predict(X_test_boston).reshape(1,-1)[0]

array([13.901374 , 20.337719 , 21.278582 , 37.597572 , 26.946499 ,
       21.38446  , 39.768806 , 25.564949 , 19.906519 , 19.899376 ,
       19.872349 , 18.18703  , 15.045628 , 41.80566  , 19.000334 ,
       21.666996 , 28.259417 , 22.9476   , 19.760763 , 19.964777 ,
       13.901375 , 14.004792 , 20.864904 , 19.66957  , 20.715708 ,
       22.533686 , 37.678093 , 29.979378 , 13.901374 , 21.38217  ,
       23.873253 , 13.901375 , 29.783869 , 22.836262 , 20.215439 ,
       13.901374 , 14.109653 , 18.163536 , 18.730417 , 25.418623 ,
       24.513168 , 29.317616 , 13.913697 , 41.728554 , 28.291185 ,
       23.22245  , 30.136227 , 19.878973 , 20.53765  , 22.463171 ,
       29.446644 , 20.255283 , 13.901427 , 14.28129  , 39.219074 ,
       27.370905 , 13.901473 , 41.805614 , 30.421799 , 22.272724 ,
       20.125593 , 13.946228 , 13.901374 , 20.368042 , 26.464693 ,
       22.94166  , 13.901375 , 24.94749  , 13.901374 , 13.901374 ,
       19.821815 , 27.90783  , 20.642256 , 13.901433 , 28.6413

In [653]:
metrics.mean_squared_error(model_boston.predict(X_test_boston).reshape(1,-1)[0],y_test_boston)

19.258438973289618

In [533]:
y_test_boston

array([ 7.2, 18.8, 19. , 27. , 22.2, 24.5, 31.2, 22.9, 20.5, 23.2, 18.6,
       14.5, 17.8, 50. , 20.8, 24.3, 24.2, 19.8, 19.1, 22.7, 12. , 10.2,
       20. , 18.5, 20.9, 23. , 27.5, 30.1,  9.5, 22. , 21.2, 14.1, 33.1,
       23.4, 20.1,  7.4, 15.4, 23.8, 20.1, 24.5, 33. , 28.4, 14.1, 46.7,
       32.5, 29.6, 28.4, 19.8, 20.2, 25. , 35.4, 20.3,  9.7, 14.5, 34.9,
       26.6,  7.2, 50. , 32.4, 21.6, 29.8, 13.1, 27.5, 21.2, 23.1, 21.9,
       13. , 23.2,  8.1,  5.6, 21.7, 29.6, 19.6,  7. , 26.4, 18.9, 20.9,
       28.1, 35.4, 10.2, 24.3, 43.1, 17.6, 15.4, 16.2, 27.1, 21.4, 21.5,
       22.4, 25. , 16.6, 18.6, 22. , 42.8, 35.1, 21.5, 36. , 21.9, 24.1,
       50. , 26.7, 25. ])

In [267]:
svr_boston=SVR()

In [268]:
svr_boston.fit(X_train_boston,y_train_boston)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='auto',
  kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [276]:
svr_boston.score(X_test_boston,y_test_boston)

-0.02242374210743403

In [285]:
from sklearn.model_selection import GridSearchCV

In [282]:
grid_search_svm=GridSearchCV(svr_boston,param_grid={'kernel':['linear','rbf'],'C':[0.1,1,10,100]})

In [284]:
rst=grid_search_svm.fit(X_train_boston,y_train_boston)

In [287]:
rst.cv_results_

d:\program files\python\lib\site-packages\sklearn\utils\deprecation.py:122: FutureWarning: You are accessing a training score ('mean_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
d:\program files\python\lib\site-packages\sklearn\utils\deprecation.py:122: FutureWarning: You are accessing a training score ('split0_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
d:\program files\python\lib\site-packages\sklearn\utils\deprecation.py:122: FutureWarning: You are accessing a training score ('split1_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
d:\program files\python\lib\site-packages\sklearn\utils\depr

{'mean_fit_time': array([1.37595256e-01, 5.98986944e-03, 1.32391032e+00, 7.33645757e-03,
        1.55650935e+01, 8.00196330e-03, 2.56709711e+01, 8.99537404e-03]),
 'mean_score_time': array([0.00099937, 0.00233905, 0.00066566, 0.00464908, 0.00100001,
        0.00266496, 0.00033355, 0.00233213]),
 'mean_test_score': array([ 0.66061849, -0.03105849,  0.65333792, -0.01255665,  0.643474  ,
         0.06858777,  0.53992006,  0.09954753]),
 'mean_train_score': array([ 0.67889624, -0.01206665,  0.69661962,  0.13151768,  0.70331837,
         0.80598586,  0.51960397,  0.99871143]),
 'param_C': masked_array(data=[0.1, 0.1, 1, 1, 10, 10, 100, 100],
              mask=[False, False, False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['linear', 'rbf', 'linear', 'rbf', 'linear', 'rbf',
                    'linear', 'rbf'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value='?',


In [289]:
svr_boston=SVR(kernel="linear",C=0.1)

In [290]:
svr_boston.fit(X_train_boston,y_train_boston,)

SVR(C=0.1, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='auto',
  kernel='linear', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [291]:
svr_boston.predict(X_test_boston)

array([ 8.17745591, 19.01883293, 22.2835033 , 26.95889927, 24.39678795,
       21.01231234, 28.50692059, 24.25533344, 19.32505957, 19.85828454,
       18.3266446 , 18.12855946, 15.98989597, 33.32782778, 16.18540684,
       20.56438956, 24.08890441, 20.92854521, 17.55895595, 20.64997014,
       10.01541527, 13.89679224, 21.7831427 , 14.1451175 , 22.74727427,
       20.36830685, 27.47921883, 27.16919442, 11.68859812, 20.97318962,
       21.75590479, 15.12952418, 31.34925173, 23.11774591, 16.75068848,
        6.07208239, 17.094847  , 20.59826876, 14.17411048, 28.11469105,
       23.48235173, 26.3592583 , 16.78700913, 33.10766282, 28.43401867,
       23.76940628, 29.29445033, 18.4758186 , 21.43716586, 23.56729132,
       31.43885609, 17.97938032, 10.06698977, 14.49805065, 31.40702085,
       26.11568953, 16.3152989 , 37.0598665 , 32.1518911 , 23.43045978,
       22.94246904, 18.69620514, 16.07226281, 21.11705048, 24.21842106,
       24.39815679, 16.3479423 , 26.20599365,  3.16134286, 10.88

In [313]:
metrics.mean_squared_error(svr_boston.predict(X_test_boston),y_test_boston)

22.375276874867165