In [1]:
import copy

In [2]:
import numpy as np

In [3]:
np.random.seed(0)

In [4]:
def sigmoid(x):
    output=1/(1+np.exp(-x))
    return output

In [39]:
def sigmoid_output_to_derivative(output):
    return output*(1-output)

In [6]:
int2binary={}

In [7]:
binary_dim=8

In [9]:
largest_number=pow(2,binary_dim)
largest_number

256

In [11]:
binary=np.unpackbits(np.array([range(largest_number)],dtype=np.uint8).T,axis=1)
binary,binary.shape

(array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 1],
        [0, 0, 0, ..., 0, 1, 0],
        ...,
        [1, 1, 1, ..., 1, 0, 1],
        [1, 1, 1, ..., 1, 1, 0],
        [1, 1, 1, ..., 1, 1, 1]], dtype=uint8), (256, 8))

In [12]:
for i in range(largest_number):
    int2binary[i]=binary[i]

In [19]:
len(int2binary)

256

In [15]:
int2binary[2]

array([0, 0, 0, 0, 0, 0, 1, 0], dtype=uint8)

In [16]:
binary[2]

array([0, 0, 0, 0, 0, 0, 1, 0], dtype=uint8)

In [17]:
int2binary

{0: array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8),
 1: array([0, 0, 0, 0, 0, 0, 0, 1], dtype=uint8),
 2: array([0, 0, 0, 0, 0, 0, 1, 0], dtype=uint8),
 3: array([0, 0, 0, 0, 0, 0, 1, 1], dtype=uint8),
 4: array([0, 0, 0, 0, 0, 1, 0, 0], dtype=uint8),
 5: array([0, 0, 0, 0, 0, 1, 0, 1], dtype=uint8),
 6: array([0, 0, 0, 0, 0, 1, 1, 0], dtype=uint8),
 7: array([0, 0, 0, 0, 0, 1, 1, 1], dtype=uint8),
 8: array([0, 0, 0, 0, 1, 0, 0, 0], dtype=uint8),
 9: array([0, 0, 0, 0, 1, 0, 0, 1], dtype=uint8),
 10: array([0, 0, 0, 0, 1, 0, 1, 0], dtype=uint8),
 11: array([0, 0, 0, 0, 1, 0, 1, 1], dtype=uint8),
 12: array([0, 0, 0, 0, 1, 1, 0, 0], dtype=uint8),
 13: array([0, 0, 0, 0, 1, 1, 0, 1], dtype=uint8),
 14: array([0, 0, 0, 0, 1, 1, 1, 0], dtype=uint8),
 15: array([0, 0, 0, 0, 1, 1, 1, 1], dtype=uint8),
 16: array([0, 0, 0, 1, 0, 0, 0, 0], dtype=uint8),
 17: array([0, 0, 0, 1, 0, 0, 0, 1], dtype=uint8),
 18: array([0, 0, 0, 1, 0, 0, 1, 0], dtype=uint8),
 19: array([0, 0, 0, 1, 0, 0, 1, 1], dtyp

In [20]:
alpha=0.1
input_dim=2
hidden_dim=16
output_dim=1

In [21]:
synapse_0=2*np.random.random((input_dim,hidden_dim))-1
synapse_0

array([[ 0.09762701,  0.43037873,  0.20552675,  0.08976637, -0.1526904 ,
         0.29178823, -0.12482558,  0.783546  ,  0.92732552, -0.23311696,
         0.58345008,  0.05778984,  0.13608912,  0.85119328, -0.85792788,
        -0.8257414 ],
       [-0.95956321,  0.66523969,  0.5563135 ,  0.7400243 ,  0.95723668,
         0.59831713, -0.07704128,  0.56105835, -0.76345115,  0.27984204,
        -0.71329343,  0.88933783,  0.04369664, -0.17067612, -0.47088878,
         0.54846738]])

In [22]:
synapse_1=2*np.random.random((hidden_dim,output_dim))-1
synapse_1

array([[-0.08769934],
       [ 0.1368679 ],
       [-0.9624204 ],
       [ 0.23527099],
       [ 0.22419145],
       [ 0.23386799],
       [ 0.88749616],
       [ 0.3636406 ],
       [-0.2809842 ],
       [-0.12593609],
       [ 0.39526239],
       [-0.87954906],
       [ 0.33353343],
       [ 0.34127574],
       [-0.57923488],
       [-0.7421474 ]])

In [23]:
synapse_h=2*np.random.random((hidden_dim,hidden_dim))-1
synapse_h

array([[-0.3691433 , -0.27257846,  0.14039354, -0.12279697,  0.97674768,
        -0.79591038, -0.58224649, -0.67738096,  0.30621665, -0.49341679,
        -0.06737845, -0.51114882, -0.68206083, -0.77924972,  0.31265918,
        -0.7236341 ],
       [-0.60683528, -0.26254966,  0.64198646, -0.80579745,  0.67588981,
        -0.80780318,  0.95291893, -0.0626976 ,  0.95352218,  0.20969104,
         0.47852716, -0.92162442, -0.43438607, -0.75960688, -0.4077196 ,
        -0.76254456],
       [-0.36403364, -0.17147401, -0.87170501,  0.38494424,  0.13320291,
        -0.46922102,  0.04649611, -0.81211898,  0.15189299,  0.8585924 ,
        -0.3628621 ,  0.33482076, -0.73640428,  0.43265441, -0.42118781,
        -0.63361728],
       [ 0.17302587, -0.95978491,  0.65788006, -0.99060905,  0.35563307,
        -0.45998405,  0.47038804,  0.92437709, -0.50249371,  0.15231467,
         0.18408386,  0.14450381, -0.55383673,  0.90549802, -0.10574924,
         0.69281734],
       [ 0.39895855, -0.4051261 ,  0

In [26]:
synapse_0_update=np.zeros_like(synapse_0)
synapse_0_update

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [27]:
synapse_1_update=np.zeros_like(synapse_1)
synapse_1_update

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [28]:
synapse_h_update=np.zeros_like(synapse_h)

In [29]:
for j in range(10000):
    a_int=np.random.randint(largest_number/2)
    a=int2binary[a_int]
    b_int=np.random.randint(largest_number/2)
    b=int2binary[b_int]
    c_int=a_int+b_int
    c=int2binary[c_int]    

In [30]:
d=np.zeros_like(c)

In [43]:
overallError=0

In [31]:
layer_2_deltas=list()
layer_1_values=list()
layer_1_values.append(np.zeros(hidden_dim))

In [47]:
for position in range(binary_dim):
    x=np.array([a[binary_dim-position-1],b[binary_dim-position-1]])
    y=np.array([c[binary_dim-position-1]])
    layer_1=sigmoid(np.dot(x,synapse_0)+np.dot(layer_1_values[-1],synapse_h))
    layer_2=sigmoid(np.dot(layer_1,synapse_1))
    layer_2_error=y-layer_2
    layer_2_deltas.append((layer_2_error)*sigmoid_output_to_derivative(layer_2))
    overallError+=np.abs(layer_2_error[0])
    d[binary_dim-position-1]=np.round(layer_2[0][0])

IndexError: invalid index to scalar variable.

IndexError: invalid index to scalar variable.