In [ ]:
''''''列表转化为矩阵
 维度 行数和列数  元素个数
    创建数组(列举元素)，指定数据类型
    创建特定数据：全零 全一  全空  连续数组  改变数据的形状  线段型数据
     
    ''''''

In [1]:
import numpy as np

In [4]:
list_a=[[1,2,3],[4,5,6]]

In [8]:
list_a[1]

[4, 5, 6]

In [10]:
A=np.array(list_a)
A

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
A.shape

(2, 3)

In [19]:
A.ndim

2

In [20]:
A.size

6

In [22]:
A[1]

array([4, 5, 6])

In [11]:
list_b=[[1,2,3],[4,5]]

In [13]:
B=np.array(list_b)
B

array([list([1, 2, 3]), list([4, 5])], dtype=object)

In [14]:
B.shape

(2,)

In [15]:
B.ndim

1

In [16]:
B.size

2

In [24]:
B[0]

[1, 2, 3]

In [25]:
C=np.array([1,2,34,5])
C

array([ 1,  2, 34,  5])

In [27]:
C=np.array([12,34,56],dtype=np.int32)

In [28]:
D=np.zeros((3,4))
D

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
E=np.ones((3,4))
E

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [32]:
F=np.empty((3,5))
F

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [40]:
F.reshape(5,3)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
G=np.arange(2,10,2)
G

array([2, 4, 6, 8])

In [38]:
G.reshape(2,2)

array([[2, 4],
       [6, 8]])

In [37]:
H=np.linspace(2,10,5)
H

array([ 2.,  4.,  6.,  8., 10.])

In [39]:
H.reshape(5,1)

array([[ 2.],
       [ 4.],
       [ 6.],
       [ 8.],
       [10.]])

In [43]:
I=np.arange(12).reshape(3,4)
I

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
I.reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])