In [1]:
import tensorflow as tf

In [2]:
sess=tf.Session()

In [3]:
###下面是读取，经测试，变量数目必须相等
peek_w_conv1=tf.Variable(tf.truncated_normal([5,5,1,32],stddev=0.1))
peek_b_conv1=tf.Variable(tf.constant(0.2,shape=[32]))
peek_w_conv2=tf.Variable(tf.truncated_normal([5,5,32,64],stddev=0.1))
peek_b_conv2=tf.Variable(tf.constant(0.2,shape=[64]))
peek_w_layer1=tf.Variable(tf.truncated_normal([7*7*64,1024],stddev=0.1))
peek_b_layer1=tf.Variable(tf.constant(0.2,shape=[1024]))
peek_w_layer2=tf.Variable(tf.truncated_normal([1024,10],stddev=0.1))
peek_b_layer2=tf.Variable(tf.constant(0.2,shape=[10]))
#peek_b_layer3=tf.Variable(tf.constant(0.2,shape=[20])) ###多一个或少一个后面加载时都会出错，形状不同也不行

In [4]:
saver=tf.train.Saver()

In [5]:
sess.run(tf.initialize_all_variables())

Instructions for updating:
Use `tf.global_variables_initializer` instead.


In [6]:
sess.run(peek_w_conv1)

array([[[[-1.39084145e-01, -6.22267835e-02, -5.49163520e-02,
           8.32758087e-04,  7.35627934e-02,  1.93558056e-02,
          -1.45205706e-01,  1.01124786e-01,  9.03466567e-02,
          -7.50606507e-02,  1.27486169e-01,  6.56543598e-02,
           1.61932558e-01,  1.08997665e-01,  1.13978572e-02,
          -1.51836917e-01,  7.19592050e-02, -5.64271174e-02,
           1.28314365e-02,  4.07782756e-02,  9.78967873e-05,
          -1.18213799e-02,  5.05395532e-02,  8.07958692e-02,
           1.20793954e-01, -1.46966383e-01, -1.83864027e-01,
           1.76095832e-02,  1.04713693e-01,  3.45075913e-02,
           6.42903447e-02,  9.88796726e-02]],

        [[ 5.59021719e-02, -9.38441679e-02,  9.50477645e-02,
          -5.56763373e-02, -1.38067991e-01, -7.94932172e-02,
          -1.81831732e-01, -1.30621782e-02, -1.24181965e-02,
          -5.77931292e-02,  9.01805982e-02,  3.32764946e-02,
          -4.32351232e-02,  1.21671138e-02, -2.92830560e-02,
          -6.95176888e-03, -1.07378483

In [7]:
saver.restore(sess,'variables/result.ckpt')

INFO:tensorflow:Restoring parameters from variables/result.ckpt


In [8]:
sess.run(peek_w_conv1)

array([[[[ 7.21422732e-02,  6.40523527e-03,  7.89451450e-02,
          -2.85129044e-02, -8.96042585e-03,  3.21494453e-02,
           8.13634542e-04,  1.32602667e-02,  1.10545140e-02,
          -8.65286291e-02, -1.82427108e-01,  5.81306927e-02,
           1.62520576e-02,  1.23548642e-01,  1.88228726e-01,
          -2.68823244e-02,  1.14327278e-02, -5.69603816e-02,
          -9.68910456e-02, -8.17167014e-02, -3.35001685e-02,
          -8.51916596e-02,  6.06359951e-02,  1.04888286e-02,
          -9.92670935e-03, -3.20322625e-02,  3.48541960e-02,
           6.58624917e-02, -6.45086169e-02,  2.41443031e-02,
           2.08184123e-02, -7.95384794e-02]],

        [[ 4.35172319e-02, -9.30572078e-02,  7.34538436e-02,
           9.67552960e-02,  1.44086331e-01,  6.42187009e-03,
          -1.87140614e-01, -1.67963982e-01, -8.18568096e-02,
          -5.38818315e-02, -1.73810735e-01,  6.67137653e-02,
          -7.12824985e-02,  4.21691239e-02, -5.71821705e-02,
           3.15764360e-02,  2.70719323

In [9]:
sess.run(peek_w_conv2)

array([[[[-7.72436783e-02,  1.46970097e-02,  9.30899195e-03, ...,
          -1.87305540e-01, -8.05167109e-02,  6.01506904e-02],
         [ 3.98634635e-02, -3.57081555e-02,  2.27989047e-04, ...,
          -3.09643894e-02, -5.52628702e-03, -1.58242926e-01],
         [-2.34319903e-02,  1.98449921e-02, -7.14920163e-02, ...,
           2.83896681e-02,  3.98427062e-02,  2.47719232e-02],
         ...,
         [ 1.15140952e-01, -1.32728800e-01,  1.55702746e-02, ...,
           6.51996061e-02,  1.31471325e-02, -4.67754379e-02],
         [-2.56459918e-02,  6.74410164e-02,  7.72501156e-02, ...,
          -3.47884349e-03, -2.37027481e-02, -8.43821242e-02],
         [ 9.50004905e-02, -2.53568422e-02, -6.22715242e-02, ...,
          -1.95901152e-02,  2.80222576e-02, -3.71854985e-03]],

        [[ 3.78199518e-02,  1.06780328e-01, -8.21937621e-02, ...,
          -2.37311777e-02, -1.21837497e-01,  5.46248257e-02],
         [ 1.72561571e-01, -5.96120656e-02,  7.08436072e-02, ...,
           1.17158435e