preprocessing 主要包含以下几种方法：
1,binarization
2,scaling
3,normalization
4,mean removal

首先是binarization

用法：preprocessing.Binarizer(threshold=1.5).transform(data)

In [1]:
from sklearn import preprocessing
import numpy as np

In [2]:
data=np.array([[2.2,5.9,-1.8],[5.4,-3.2,-5.1],[-1.9,4.2,3.2]])

In [3]:
data

array([[ 2.2,  5.9, -1.8],
       [ 5.4, -3.2, -5.1],
       [-1.9,  4.2,  3.2]])

In [4]:
bindata=preprocessing.Binarizer(threshold=1.5).transform(data)

In [5]:
bindata

array([[1., 1., 0.],
       [1., 0., 0.],
       [0., 1., 1.]])

接下来是mean removal?scale?

用法：preprocessing.scale(data)

In [6]:
print('mean(before)=',data.mean(axis=0))
print('standard deviation(before)=',data.std(axis=0))

mean(before)= [ 1.9         2.3        -1.23333333]
standard deviation(before)= [2.98775278 3.95052739 3.41207008]


In [9]:
scaled_data=preprocessing.scale(data)
print('mean(after)=',scaled_data.mean(axis=0))
print('standard deviation(after)=',scaled_data.std(axis=0))

mean(after)= [0.00000000e+00 0.00000000e+00 7.40148683e-17]
standard deviation(after)= [1. 1. 1.]


In [10]:
scaled_data

array([[ 0.10040991,  0.91127074, -0.16607709],
       [ 1.171449  , -1.39221918, -1.1332319 ],
       [-1.27185891,  0.48094844,  1.29930899]])

下面是scaling，包含：1 StandardScaler,2 MinMaxScaler,3 Normalizer（只有minmaxscaler？）

用法：preprocessing.MinMaxScaler(feature_range=(0,1)).fit_transform(data)

In [17]:
data

array([[ 2.2,  5.9, -1.8],
       [ 5.4, -3.2, -5.1],
       [-1.9,  4.2,  3.2]])

In [40]:
preprocessing.MinMaxScaler(feature_range=(0,1)).fit_transform(data)

array([[0.56164384, 1.        , 0.39759036],
       [1.        , 0.        , 0.        ],
       [0.        , 0.81318681, 1.        ]])

最后是normalization，只进行水平运算？

包含L1、L2两种，L1是每行绝对值和为1，L2是每行平方和为1，比例均不变

用法：preprocessing.normalize(data,norm='l1')

In [21]:
data

array([[ 2.2,  5.9, -1.8],
       [ 5.4, -3.2, -5.1],
       [-1.9,  4.2,  3.2]])

In [22]:
preprocessing.normalize(data,norm='l1')

array([[ 0.22222222,  0.5959596 , -0.18181818],
       [ 0.39416058, -0.23357664, -0.37226277],
       [-0.20430108,  0.4516129 ,  0.34408602]])

In [23]:
preprocessing.normalize(data,norm='l2')

array([[ 0.3359268 ,  0.90089461, -0.2748492 ],
       [ 0.6676851 , -0.39566524, -0.63059148],
       [-0.33858465,  0.74845029,  0.57024784]])

下面是encoding部分

首先是label encoding

步骤：1 import（preprocessing即可），2 实例化，3 fit， 4transform

In [42]:
labels=['setosa','versicolor','virginica']

In [43]:
encoder=preprocessing.LabelEncoder()

In [44]:
encoder.fit(labels)

LabelEncoder()

In [45]:
for i,item in enumerate(encoder.classes_):  ##注意这里迭代器的用法
    print(item,'=>',i)

setosa => 0
versicolor => 1
virginica => 2


In [54]:
more_labels=['versicolor','versicolor','virginica','setosa','versicolor']
more_labels_encoded=encoder.transform(more_labels)
more_labels_encoded

array([1, 1, 2, 0, 1], dtype=int64)

In [55]:
list(more_labels_encoded)

[1, 1, 2, 0, 1]

然后是one-hot encoding

In [56]:
import pandas as pd
from IPython.display import display

In [59]:
data=pd.read_csv('adult.data',header=None,index_col=False,names=['age','workclass','fnlwgt',
                                                                'education','education-num',
                                                                'martial-status','occupation',
                                                                'relationship','race','gender',
                                                                'capital-gain','capital-loss',
                                                                'hours-per-week','native-country',
                                                                'income'])

In [60]:
data.head()

age          workclass  fnlwgt   education  education-num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   

        martial-status          occupation    relationship    race   gender  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loss  hours-per-week  native-country  income  
0          2174             0              40   United-States   <=50K  
1             0             0              13   United-States   <=50K  
2             0             0              40   United-States   <=50K  
3             0             0              40   United-States   <=50K  
4             0             0              40            Cuba   <=50K

In [72]:
data=data[['age','workclass','education','gender','hours-per-week','occupation','income']]

In [73]:
data.head()

age          workclass   education   gender  hours-per-week  \
0   39          State-gov   Bachelors     Male              40   
1   50   Self-emp-not-inc   Bachelors     Male              13   
2   38            Private     HS-grad     Male              40   
3   53            Private        11th     Male              40   
4   28            Private   Bachelors   Female              40   

           occupation  income  
0        Adm-clerical   <=50K  
1     Exec-managerial   <=50K  
2   Handlers-cleaners   <=50K  
3   Handlers-cleaners   <=50K  
4      Prof-specialty   <=50K

In [105]:
print('original features:\n',list(data.columns),'\n')
data_dummies=pd.get_dummies(data)             ###貌似这个方法不大好，还不如直接对其中一行或几行做get_dummies
print('features after one-hot encoding:\n',list(data_dummies.columns))

original features:
 ['age', 'workclass', 'education', 'gender', 'hours-per-week', 'occupation', 'income'] 

features after one-hot encoding:
 ['age', 'hours-per-week', 'workclass_ ?', 'workclass_ Federal-gov', 'workclass_ Local-gov', 'workclass_ Never-worked', 'workclass_ Private', 'workclass_ Self-emp-inc', 'workclass_ Self-emp-not-inc', 'workclass_ State-gov', 'workclass_ Without-pay', 'education_ 10th', 'education_ 11th', 'education_ 12th', 'education_ 1st-4th', 'education_ 5th-6th', 'education_ 7th-8th', 'education_ 9th', 'education_ Assoc-acdm', 'education_ Assoc-voc', 'education_ Bachelors', 'education_ Doctorate', 'education_ HS-grad', 'education_ Masters', 'education_ Preschool', 'education_ Prof-school', 'education_ Some-college', 'gender_ Female', 'gender_ Male', 'occupation_ ?', 'occupation_ Adm-clerical', 'occupation_ Armed-Forces', 'occupation_ Craft-repair', 'occupation_ Exec-managerial', 'occupation_ Farming-fishing', 'occupation_ Handlers-cleaners', 'occupation_ Machine

In [107]:
data_dummies.head()

age  hours-per-week  workclass_ ?  workclass_ Federal-gov  \
0   39              40             0                       0   
1   50              13             0                       0   
2   38              40             0                       0   
3   53              40             0                       0   
4   28              40             0                       0   

   workclass_ Local-gov  workclass_ Never-worked  workclass_ Private  \
0                     0                        0                   0   
1                     0                        0                   0   
2                     0                        0                   1   
3                     0                        0                   1   
4                     0                        0                   1   

   workclass_ Self-emp-inc  workclass_ Self-emp-not-inc  workclass_ State-gov  \
0                        0                            0                     1   
1                        0                            1                     0   
2                        0                            0                     0   
3                        0                            0                     0   
4                        0                            0                     0   

       ...       occupation_ Machine-op-inspct  occupation_ Other-service  \
0      ...                                   0                          0   
1      ...                                   0                          0   
2      ...                                   0                          0   
3      ...                                   0                          0   
4      ...                                   0                          0   

   occupation_ Priv-house-serv  occupation_ Prof-specialty  \
0                            0                           0   
1                            0                           0   
2                            0                           0   
3                            0                           0   
4                            0                           1   

   occupation_ Protective-serv  occupation_ Sales  occupation_ Tech-support  \
0                            0                  0                         0   
1                            0                  0                         0   
2                            0                  0                         0   
3                            0                  0                         0   
4                            0                  0                         0   

   occupation_ Transport-moving  income_ <=50K  income_ >50K  
0                             0              1             0  
1                             0              1             0  
2                             0              1             0  
3                             0              1             0  
4                             0              1             0  

[5 rows x 46 columns]

In [98]:
dummies_occupation=pd.get_dummies(data['occupation'])

In [118]:
data.occupation.value_counts()

 Prof-specialty       4140
 Craft-repair         4099
 Exec-managerial      4066
 Adm-clerical         3770
 Sales                3650
 Other-service        3295
 Machine-op-inspct    2002
 ?                    1843
 Transport-moving     1597
 Handlers-cleaners    1370
 Farming-fishing       994
 Tech-support          928
 Protective-serv       649
 Priv-house-serv       149
 Armed-Forces            9
Name: occupation, dtype: int64

In [108]:
dummies_occupation

?   Adm-clerical   Armed-Forces   Craft-repair   Exec-managerial  \
0       0              1              0              0                 0   
1       0              0              0              0                 1   
2       0              0              0              0                 0   
3       0              0              0              0                 0   
4       0              0              0              0                 0   
5       0              0              0              0                 1   
6       0              0              0              0                 0   
7       0              0              0              0                 1   
8       0              0              0              0                 0   
9       0              0              0              0                 1   
10      0              0              0              0                 1   
11      0              0              0              0                 0   
12      0              1              0              0                 0   
13      0              0              0              0                 0   
14      0              0              0              1                 0   
15      0              0              0              0                 0   
16      0              0              0              0                 0   
17      0              0              0              0                 0   
18      0              0              0              0                 0   
19      0              0              0              0                 1   
20      0              0              0              0                 0   
21      0              0              0              0                 0   
22      0              0              0              0                 0   
23      0              0              0              0                 0   
24      0              0              0              0                 0   
25      0              0              0              0                 0   
26      0              0              0              1                 0   
27      1              0              0              0                 0   
28      0              0              0              0                 1   
29      0              0              0              1                 0   
...    ..            ...            ...            ...               ...   
32531   1              0              0              0                 0   
32532   0              0              0              0                 0   
32533   0              0              0              0                 1   
32534   0              1              0              0                 0   
32535   0              0              0              0                 0   
32536   0              0              0              0                 1   
32537   0              0              0              1                 0   
32538   0              0              0              0                 0   
32539   1              0              0              0                 0   
32540   0              1              0              0                 0   
32541   1              0              0              0                 0   
32542   1              0              0              0                 0   
32543   0              0              0              0                 0   
32544   0              0              0              0                 0   
32545   0              1              0              0                 0   
32546   0              0              0              0                 0   
32547   0              0              0              0                 0   
32548   0              0              0              0                 0   
32549   0              1              0              0                 0   
32550   0              0              0              1                 0   
32551   0              0              0              0  

In [113]:
dummies_gender_income=pd.get_dummies(data[['gender','income']])

In [114]:
dummies_gender_income

gender_ Female  gender_ Male  income_ <=50K  income_ >50K
0                   0             1              1             0
1                   0             1              1             0
2                   0             1              1             0
3                   0             1              1             0
4                   1             0              1             0
5                   1             0              1             0
6                   1             0              1             0
7                   0             1              0             1
8                   1             0              0             1
9                   0             1              0             1
10                  0             1              0             1
11                  0             1              0             1
12                  1             0              1             0
13                  0             1              1             0
14                  0             1              0             1
15                  0             1              1             0
16                  0             1              1             0
17                  0             1              1             0
18                  0             1              1             0
19                  1             0              0             1
20                  0             1              0             1
21                  1             0              1             0
22                  0             1              1             0
23                  0             1              1             0
24                  1             0              1             0
25                  0             1              0             1
26                  0             1              1             0
27                  0             1              0             1
28                  0             1              1             0
29                  0             1              1             0
...               ...           ...            ...           ...
32531               1             0              1             0
32532               0             1              0             1
32533               0             1              0             1
32534               1             0              1             0
32535               0             1              1             0
32536               1             0              0             1
32537               0             1              1             0
32538               1             0              0             1
32539               0             1              0             1
32540               1             0              1             0
32541               1             0              1             0
32542               0             1              1             0
32543               1             0              1             0
32544               1             0              1             0
32545               1             0              0             1
32546               1             0              1             0
32547               0             1              1             0
32548               0             1              1             0
32549               1             0              1             0
32550               0             1              1             0
32551               0             1              1             0
32552               0             1              1             0
32553               0             1              1             0
32554               0             1              0             1
32555               0             1              1             0
32556               1             0              1             0
32557               0             1              0             1
32558               1             0              1             0
32559               0             1              1             0
32560               1             0       

In [115]:
features=data_dummies.ix[:,'age':'occupation_ Transport-moving']###原课堂讲法，感觉更乱，所有的feature都one-hot处理了

c:\users\dell\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


In [81]:
X=features.values
y=data_dummies['income_ >50K'].values

In [82]:
X

array([[39, 40,  0, ...,  0,  0,  0],
       [50, 13,  0, ...,  0,  0,  0],
       [38, 40,  0, ...,  0,  0,  0],
       ...,
       [58, 40,  0, ...,  0,  0,  0],
       [22, 20,  0, ...,  0,  0,  0],
       [52, 40,  0, ...,  0,  0,  0]], dtype=int64)

In [85]:
y

array([0, 0, 0, ..., 0, 0, 1], dtype=uint8)

In [86]:
from sklearn.linear_model import LogisticRegression

In [87]:
from sklearn.model_selection import train_test_split

In [88]:
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=0)

In [89]:
logreg=LogisticRegression()

In [90]:
logreg.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [96]:
print('logistic regression score on the test sset: {:.2f}'.format(logreg.score(X_test,y_test)))

logistic regression score on the test sset: 0.81
