In [1]:
import tensorflow as tf
import numpy as np

In [2]:
zeros=tf.zeros([1])

In [3]:
zeros

<tf.Tensor 'zeros:0' shape=(1,) dtype=float32>

In [4]:
sess=tf.Session()

In [5]:
a=sess.run(zeros)

In [6]:
a

array([0.], dtype=float32)

In [9]:
vrb=tf.Variable(tf.zeros([1]))

In [24]:
sess.run(tf.initialize_all_variables())

In [14]:
vrb

<tf.Variable 'Variable_1:0' shape=(1,) dtype=float32_ref>

In [15]:
vrb2=tf.Variable(tf.zeros([1]))

In [17]:
vrb2

<tf.Variable 'Variable_2:0' shape=(1,) dtype=float32_ref>

In [37]:
sess.run(tf.initialize_all_variables())

In [25]:
sess.run(vrb2)

array([0.], dtype=float32)

In [36]:
vrb6=tf.Variable(tf.zeros([1]))

In [39]:
sess.run(vrb7)

NameError: name 'vrb7' is not defined

In [40]:
vrb7=tf.Variable(tf.zeros([1]))

In [43]:
sess.run(vrb7)

FailedPreconditionError: Attempting to use uninitialized value Variable_7
	 [[Node: _retval_Variable_7_0_0 = _Retval[T=DT_FLOAT, index=0, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Variable_7)]]

In [44]:
vrb8=tf.Variable(tf.zeros([1]))

In [45]:
vrb8

<tf.Variable 'Variable_8:0' shape=(1,) dtype=float32_ref>

In [46]:
sess.run(tf.initialize_all_variables())

In [47]:
vrb8

<tf.Variable 'Variable_8:0' shape=(1,) dtype=float32_ref>

In [48]:
sess.run(vrb8)

array([0.], dtype=float32)

In [49]:
vrb8

<tf.Variable 'Variable_8:0' shape=(1,) dtype=float32_ref>

In [50]:
aa=tf.reduce_mean(vrb-3)

In [51]:
aa

<tf.Tensor 'Mean:0' shape=() dtype=float32>

In [52]:
sess.run(aa)

-3.0

In [66]:
vrbs=tf.Variable(tf.zeros([3,4]))

In [81]:
vrbs2=tf.Variable(tf.zeros(2,3))

In [82]:
sess.run(tf.initialize_all_variables())

In [68]:
sess.run(vrbs)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)

In [84]:
sess.run(vrbs2)

array([0, 0])

In [106]:
optimizer=tf.train.GradientDescentOptimizer(0.5)

In [113]:
aa2=tf.reduce_mean(tf.square(vrb-5))

In [114]:
sess.run(aa2)

25.0

In [118]:
sess.run(tf.reduce_mean(tf.square(5-3)))

4

In [119]:
train=optimizer.minimize(aa2)

In [120]:
sess.run(train)

In [92]:
aa2

<tf.Tensor 'Mean_1:0' shape=() dtype=float32>

In [123]:
sess.run(vrb)

array([5.], dtype=float32)

In [124]:
sess.run(aa2)

0.0

In [131]:
x0=tf.Variable(tf.ones([1,3]))

In [132]:
y0=tf.Variable(tf.ones([1,3]))

In [128]:
x_list=[0,1,0]
y_list=[0,0,1]

In [133]:
diff=tf.reduce_mean(tf.square(x0-x_list)+tf.square(y0-y_list))

In [135]:
optimizer=tf.train.GradientDescentOptimizer(0.5)

In [137]:
train=optimizer.minimize(diff)

In [139]:
sess.run(tf.initialize_all_variables())

In [140]:
sess.run(x0)

array([[1., 1., 1.]], dtype=float32)

In [141]:
sess.run(diff)

1.3333334

In [142]:
sess.run(train)

In [143]:
sess.run(x0)

array([[0.6666666, 1.       , 0.6666666]], dtype=float32)

In [145]:
sess.run(y0)

array([[0.6666666, 0.6666666, 1.       ]], dtype=float32)

In [144]:
sess.run(diff)

0.59259254

In [146]:
sess.run(train)

In [147]:
sess.run(x0)

array([[0.44444442, 1.        , 0.44444442]], dtype=float32)

In [148]:
sess.run(diff)

0.26337445

In [179]:
sess.run(train)#这是因为错误的把x0，y0设为三个元素不相同的Variable，所以得到最终下x0，y0变成了一维向量而不是一个数值

In [180]:
sess.run(x0)

array([[0.00513823, 1.        , 0.00513823]], dtype=float32)

In [181]:
sess.run(diff)

3.5201858e-05

In [195]:
x0=tf.Variable(tf.ones([1],dtype=tf.float32))
y0=tf.Variable(tf.ones([1],dtype=tf.float32))

In [196]:
vct=np.array([1,1,1],dtype=np.float)

In [197]:
diff=tf.reduce_mean(tf.square(x0*vct-x_list)+tf.square(y0*vct-y_list))

In [198]:
train=optimizer.minimize(diff)

In [201]:
sess.run(tf.initialize_all_variables())

In [202]:
sess.run(x0)

array([1.], dtype=float32)

In [203]:
sess.run(diff)

1.3333334

In [204]:
sess.run(train)

In [205]:
sess.run(x0)

array([0.3333333], dtype=float32)

In [206]:
sess.run(diff)

0.44444445

In [207]:
sess.run(x0)

array([0.3333333], dtype=float32)

In [208]:
sess.run(diff)

0.44444445

In [209]:
sess.run(y0)

array([0.3333333], dtype=float32)

In [210]:
tf.__version__

'1.7.0'

In [211]:
x_data=np.random.rand(100).astype(np.float32)

In [212]:
y_data=2*x_data**2+3*x_data+1

In [213]:
y_data

array([2.60782  , 5.3395085, 1.4789052, 1.7278118, 3.6437373, 1.5275302,
       4.710637 , 1.9284792, 1.3751793, 1.2899168, 1.6298435, 5.4675655,
       2.5213416, 5.732567 , 1.1395271, 5.862548 , 4.929756 , 3.7009122,
       3.6232517, 4.9469066, 2.7148907, 3.7940946, 3.0698233, 1.3182986,
       4.89108  , 5.6807365, 1.9403646, 2.2870486, 4.050234 , 2.2819214,
       2.9939203, 1.4653605, 1.2112007, 3.3173056, 2.4799118, 5.800981 ,
       4.837597 , 1.5088263, 4.2596636, 4.063359 , 1.6995978, 5.9508667,
       1.7060295, 3.3559713, 1.032738 , 4.4023952, 1.0812532, 1.4957501,
       3.4784195, 1.7086229, 2.7877064, 5.5614557, 3.3589287, 2.3921041,
       4.4807634, 5.4626985, 2.423381 , 5.6032763, 1.3826449, 1.427394 ,
       5.0593586, 5.376373 , 1.6287775, 2.0626526, 3.110157 , 3.4099998,
       1.9108924, 4.2502985, 1.1090317, 2.3406231, 3.0832818, 4.1885777,
       4.1803794, 2.1135736, 4.465107 , 5.183523 , 3.2309036, 2.9699867,
       5.7574644, 1.9943748, 1.3790476, 5.431288 , 

In [214]:
a0=tf.Variable(tf.random_uniform([1],-4,4),dtype=tf.float32)

In [215]:
b0=tf.Variable(tf.random_uniform([1],-4,4),dtype=tf.float32)

In [216]:
c0=tf.Variable(tf.random_uniform([1],-4,4),dtype=tf.float32)

In [217]:
diff=tf.reduce_mean(tf.square(a0*x_data**2+b0*x_data+c0-y_data))

In [218]:
train=optimizer.minimize(diff)

In [219]:
sess.run(tf.initialize_all_variables())

In [220]:
sess.run(a0),sess.run(b0),sess.run(c0),sess.run(diff)

(array([-0.94276905], dtype=float32),
 array([0.18752575], dtype=float32),
 array([-1.173377], dtype=float32),
 24.760008)

In [221]:
for step in range(201):
    sess.run(train)
    if step//10==0:
        print(step,sess.run(a0),sess.run(b0),sess.run(c0),sess.run(diff))

0 [1.2358005] [3.103532] [3.4957566] 5.2370133
1 [0.49365306] [1.9825528] [1.2166462] 1.2841957
2 [1.0244945] [2.6381872] [2.0590754] 0.44162494
3 [0.96293366] [2.4823394] [1.5321387] 0.2303485
4 [1.1434659] [2.6709156] [1.6345441] 0.15480922
5 [1.1969396] [2.6909325] [1.4731371] 0.11414113
6 [1.2902827] [2.7729037] [1.4438722] 0.086446136
7 [1.3512073] [2.815752] [1.3684536] 0.065950125
8 [1.4137713] [2.865972] [1.3247409] 0.050417036
9 [1.464406] [2.9041078] [1.2766341] 0.03857034


In [222]:
for step in range(2001):
    sess.run(train)
    if step//50==0:
        print(step,sess.run(a0),sess.run(b0),sess.run(c0),sess.run(diff))

0 [1.8916246] [3.114612] [0.97896546] 6.4227206e-05
1 [1.8918995] [3.1143215] [0.97901875] 6.3901425e-05
2 [1.8921736] [3.1140316] [0.9790719] 6.357711e-05
3 [1.8924471] [3.1137424] [0.97912496] 6.325554e-05
4 [1.8927199] [3.1134539] [0.9791779] 6.293505e-05
5 [1.8929919] [3.113166] [0.9792307] 6.261552e-05
6 [1.8932633] [3.112879] [0.9792834] 6.229897e-05
7 [1.8935341] [3.1125927] [0.979336] 6.19836e-05
8 [1.8938041] [3.112307] [0.9793884] 6.167014e-05
9 [1.8940735] [3.1120224] [0.9794408] 6.1357074e-05
10 [1.8943421] [3.1117382] [0.9794928] 6.104634e-05
11 [1.89461] [3.111455] [0.9795449] 6.0737046e-05
12 [1.8948773] [3.1111722] [0.9795967] 6.0429164e-05
13 [1.895144] [3.1108902] [0.9796485] 6.0122915e-05
14 [1.89541] [3.1106088] [0.9797001] 5.9818456e-05
15 [1.8956752] [3.1103284] [0.97975165] 5.9515573e-05
16 [1.8959397] [3.1100485] [0.97980297] 5.9213606e-05
17 [1.8962036] [3.1097693] [0.97985417] 5.8913916e-05
18 [1.896467] [3.109491] [0.97990537] 5.861543e-05
19 [1.8967295] [3.1

In [223]:
for step in range(10001):
    sess.run(train)
    if step//100==0:
        print(step,sess.run(a0),sess.run(b0),sess.run(c0),sess.run(diff))

0 [1.9993262] [3.0007124] [0.9998693] 2.48321e-09
1 [1.9993279] [3.0007105] [0.9998696] 2.4707618e-09
2 [1.9993297] [3.0007088] [0.99987] 2.460659e-09
3 [1.9993314] [3.000707] [0.9998703] 2.4461966e-09
4 [1.9993331] [3.0007052] [0.99987066] 2.432711e-09
5 [1.9993348] [3.0007033] [0.99987084] 2.4204203e-09
6 [1.9993366] [3.0007017] [0.9998713] 2.4061426e-09
7 [1.9993383] [3.0006998] [0.99987155] 2.391899e-09
8 [1.9993399] [3.000698] [0.9998719] 2.3867506e-09
9 [1.9993416] [3.0006964] [0.99987227] 2.372528e-09
10 [1.9993433] [3.0006945] [0.9998725] 2.3557016e-09
11 [1.999345] [3.0006928] [0.99987286] 2.3517372e-09
12 [1.9993466] [3.0006912] [0.99987316] 2.3364644e-09
13 [1.9993483] [3.0006893] [0.99987346] 2.3208622e-09
14 [1.99935] [3.0006876] [0.99987376] 2.3131408e-09
15 [1.9993516] [3.000686] [0.9998741] 2.2989701e-09
16 [1.9993532] [3.000684] [0.99987435] 2.2926618e-09
17 [1.9993548] [3.0006824] [0.99987483] 2.27619e-09
18 [1.9993564] [3.0006807] [0.99987507] 2.2667033e-09
19 [1.999